AgResearch/gbs_prism

run_kgd.R
Beta-binomial model fitting and InbCompare plot only done for samples with depth > mindepth.bb, currently set to 0.1
=> Update beta binomial fitting & plotting in run_kgd.R

make_cohort_pages.py
I've edited the HWdgm.05 narratives to note that SNPs  lanes have been combined (if relevant).
I haven't explicitly stated that other plots have lanes split (if that's how the data is given).
=> KGD narratives

run_kgd.R
Use knowledge that seqID is composed of 5 parts with _ separators and allow the first part (SampleID) to contain _
=> allow _ in SampleID in run_kgd.R

_run_gbs_qc
added echo following `read answer` to echo User response or default parameters.
=> added echo answer to read_answer_with_default()

run_GUSbase.R, run_kgd.R
Included a seed value for random number generation in run_KGD.R and run_GUSbase.R scripts.
Important for reproducibility in methods which use random sampling such as calculating the alpha value (beta-binomial fitted parameter) for a library.
=> set.seed() included for pseudorandom number generation

SelfRelDepth.r
I just noticed there was another R script which uses built-in R functions (lm, coef, anova). I don't know with certainty that they use "randomness", but I thought it wouldn't hurt to set.seed() anyway.
=> Another r script which may benefit from set.seed()

make_cohort_pages.py
Descriptor for updated InbCompare.png
=> InbCompare mouse-over

ag_gbs_qc_prism.sh
adding --interactive to multiqc call in ag_gbs_qc_prism.sh to force rendering of interactive report.
=> adding --interactive to multiqc call in ag_gbs_qc_prism.sh

flake.nix
=> Add poppler_utils

flake.lock
To stop the Java environment module breaking things.
Fixes #53
=> Bump tassel3 dependency for more robust wrapProgram

pipeline.py
=> Loiter after task failure until all others are done or failed

pipeline.py, src/agr/gbs_prism/kgd.py, src/agr/gbs_prism/redun/peacock.py, src/agr/gbs_prism/redun/stage1.py, src/agr/gbs_prism/redun/stage2.py, src/agr/gbs_prism/tassel3.py, src/agr/redun/cluster_executor.py, src/agr/redun/util.py, src/agr/seq/multiqc.py, src/agr/util/cluster.py, src/agr/util/subprocess.py
Python 3.9+ has built-in list, dict, set, tuple
This is a simple follow-up PR to the big Slurm one, to be merged to main after that.
=> Use modern type names

flake.lock, flake.nix
Devtool for Slurm efficiency, merge this after Slurm PR
=> Seffs in devshell

config/eri-executor.jsonnet
It failed previously on one run, this seems to be OK.
=> tassel3_FastqToTagCount Slurm job a bit bigger

flake.lock, flake.nix, src/agr/gbs_prism/collate_tags_reads.py, src/agr/gbs_prism/redun/stage2.py, src/agr/redun/__init__.py, src/agr/redun/tasks/__init__.py, src/agr/redun/tasks/collate_tags_reads.py, src/agr/redun/tasks/gupdate.py, src/agr/redun/tasks/kgd.py, src/agr/redun/util.py, src/agr/util/__init__.py, src/agr/util/file_hash.py, src/agr/util/map_columns.py, src/agr/util/tests/test_map_columns.py
Fixes #61
Fixes #79 
Warehousing will follow, and has been broken off into a separate issue.
=> Database updates with qc metrics

context/eri-dev.json, context/eri-test.json, context/home.json, context/home.tiny.json, context/legacy-hpc-playpen.json, flake.lock, flake.nix, pipeline.py, src/agr/gbs_prism/redun/__init__.py, src/agr/gbs_prism/redun/warehouse.py
=> Warehousing

src/agr/gbs_prism/redun/stage2.py, src/agr/redun/cluster_executor.py, src/agr/redun/tasks/collate_tags_reads.py, src/agr/redun/tasks/gupdate.py, src/agr/redun/tasks/gusbase.py, src/agr/redun/tasks/kgd.py
Now KGD failures due to insufficient SNPs are not fatal for the overall run.
This doesn't yet format the error message into the reports - that will be a follow-up PR.
Fixes #63
=> Catch KGD failure

src/agr/gbs_prism/redun/stage2.py, src/agr/redun/cluster_executor.py, src/agr/redun/tasks/collate_tags_reads.py, src/agr/redun/tasks/gupdate.py, src/agr/redun/tasks/gusbase.py, src/agr/redun/tasks/kgd.py, src/agr/redun/tasks/tassel3.py
Fixes broken links in the HTML reports
=> Preserve same directory structure for unblinded as blinded

src/agr/redun/tasks/kgd.py
=> Copy the KgdOutput vars before removing ok and kgd_stderr

src/agr/redun/cluster_executor.py
Just removal of unused code that I wanted to keep for possible future improvement.
But it's enough to have it in the git history.
MERGE AFTER missing-output-files
=> Remove cluster executor scheduler jobs and promises

flake.lock, src/agr/gbs_prism/redun/stage2.py, src/agr/redun/tasks/gupdate.py
Bumped flake for updated gquery, needed to be able to pass cohort via predicates rather than have it stumble on an unexpected filename.
Fixes #117
=> Add import_gbs_kgd_cohort_stats

src/agr/redun/cluster_executor.py, src/agr/redun/tasks/tassel3.py
=> Make cluster executor tasks plain functions

src/agr/redun/tasks/kgd.py
The error message was spurious.  It was because of something being a task which no longer should be.
There are more instances of things which should no longer be tasks.  Will follow up with another PR.
=> Fix KGD so-called configuration error with NoneType

src/agr/gbs_prism/redun/stage2.py, src/agr/redun/tasks/gupdate.py
A single task rather than one per cohort
Fixes #117
Still waiting to see it run ...
=> Consolidated import of collated tag counts

flake.lock, flake.nix, src/run_kgd.R
Fixes #121
Haven't run this one yet, since every task is running from scratch. Will report back here when I've seen it work correctly.
=> Flip KGD plate plots

pipeline.py, src/agr/gbs_prism/redun/stage2.py, src/agr/gbs_prism/redun/warehouse.py, src/agr/redun/tasks/gupdate.py
Merge after consolidated import PR, which this is stacked on top of
=> Warehouse dependency

.github/workflows/test-suite.yml, flake.nix
This runs the few tests we have on every pull request and push to main.
I checked it by breaking a test.  It does indeed fail.
=> GitHub action to run tests

pipeline.py, src/agr/gbs_prism/job_attributes.py, src/agr/gbs_prism/redun/stage1.py, src/agr/gbs_prism/redun/stage2.py, src/agr/redun/__init__.py, src/agr/redun/cluster_executor.py, src/agr/redun/job_attributes.py, src/agr/redun/tasks/bcl_convert.py, src/agr/redun/tasks/bwa.py, src/agr/redun/tasks/cutadapt.py, src/agr/redun/tasks/dedupe.py, src/agr/redun/tasks/fake_bcl_convert.py, src/agr/redun/tasks/fastq_sample.py, src/agr/redun/tasks/fastqc.py, src/agr/redun/tasks/gusbase.py, src/agr/redun/tasks/kgd.py, src/agr/redun/tasks/kmer_analysis.py, src/agr/redun/tasks/multiqc.py, src/agr/redun/tasks/tassel3.py, src/agr/util/path.py
Mostly just passing `job_attributes` through to all cluster jobs.
=> Annotate all Slurm jobs with run and cohort

flake.nix
=> Create $GQUERY_ROOT and $GENO_ROOT in module load

src/agr/redun/tasks/tassel3.py
=> Remove any old tagCounts before making new ones
