src/agr/gbs_prism/redun/stage1.py

So deleting it can trigger re-runs of downstream tasks.
Fixes #66

Make target-spec.json file known to redun

---

src/agr/gbs_prism/redun/stage2.py
src/agr/redun/tasks/__init__.py
src/agr/redun/tasks/kgd.py
src/agr/redun/tasks/unblind.py

updating the naming convention for the sed script
updating sytnax for consistency
extending the KGD class to track all needed files
attempting to collect KGD output Files as a list of Files for unblind_all
removing list comprehension from unblind_all parameters
attempting to track KGDstdout
reverting the KGD stdout and stderr log paths
debuggin list comprehension for kgd_unblind
Fix KGD blinded files list using lazy_map
Redun lazy expressions means that inline list comprehensions don't work.  See e.g. other uses of lazy_map.

Extending KgdOutput class and adding unblind tasks

---

config/eri-executor.jsonnet
src/agr/redun/tasks/bcl_convert.py

removing unnecessary paths form the BclconvertPaths class and refoactoring how the stdout and stderr are established.

Bclconvert cleanup

---

src/agr/redun/tasks/bcl_convert.py

Simply fix them as siblings of out_dir, without relying on knowledge about the overall directory structure.

Simplify out/error paths

---

src/agr/redun/tasks/bcl_convert.py
src/agr/redun/tasks/fake_bcl_convert.py
src/agr/redun/tasks/sample_sheet.py

Essentially, bcl-convert expects to create the output directory in which it will write all files.
If this exists already, we get an error--the expected behaviour.
The method in BclConvertPaths to create the output directory causes a conflict as this was creating the out_dir before bclconvert resulting in an error. This method and call was removed.
bclconvert.stdout and bclconvert.stderr where shifted to SampleSheet/ as they can't be created prior to bclconvert creating the output directory. 
We can now delete bclconvert/ and rerun without issues, and we get the expected behaviour when the out_dir already exists.
Fixes #91

Bclconvert patch to remove --force and shifted stdout and stderr out of the untouchable bclconvert out_dir

---

flake.nix
pipeline.py
src/agr/gbs_prism/paths.py
src/agr/gbs_prism/redun/__init__.py
src/agr/gbs_prism/redun/reports.py
src/agr/gbs_prism/redun/stage2.py
src/agr/gbs_prism/redun/stage3.py
src/agr/redun/__init__.py
src/agr/redun/tasks/__init__.py
src/agr/redun/tasks/barcode_yields.py
src/agr/redun/tasks/collate_barcode_yields.py
src/agr/redun/tasks/samtools.py
src/agr/redun/tasks/tags.py
src/agr/redun/tasks/tassel3.py
src/agr/redun/util.py
src/agr/util/image.py
src/barcode_yields_plots.R
src/tag_count_plots.R

These are not yet referenced from the peacock plot, that's next to be done.
Introduced Stage 3, which consolidates output across the cohorts.  A couple of tag read summary files which were previously being generated per cohort have now been fixed to collate across cohorts as per legacy gbs_prism.
Various Python and R scripts extracted from legacy gbs_prism and seq_prisms, ported to Python 3, fixed and tidied up.
Fixes #58

Add the missing summary files and plots in the html directory

---

src/agr/redun/tasks/bcl_convert.py

This seems necessary to cope with reruns of redun.
Not yet tested.  Will do so before merging.
If you want to subsume this into your sample sheet update changes and test altogether, please go ahead, and we can close this PR.

Remove existing directory before running bcl-convert

---

src/agr/redun/tasks/bcl_convert.py

This reverts commit bd4902151046c8ed490f1809bcd38b8d3983d5f9.
This seemed to cause bcl_convert to be retriggered gratuitously.

Revert "Remove existing directory before running bcl-convert (#104)"

---

README.md
context/eri-prod.json
flake.nix

Ultimately we will have a deployment that doesn't require a local clone of the git repo.  But for now, this enables switching between environments as described in the README.
Also, first attempt at `eri-prod.json` context, we may want to tweak that.
Fastq link farm needs more thought, but we can always move the links later.  Same comment for keyfiles dir.
I am concerned about the backup and geno import dirs, as these would seem to break if two people are running at the same time.  But it has always been like that.
These directories need to be created by hand before the production run (if that's what we decide to go with):
```
"keyfiles_dir": "/agr/persist/projects/2024_illumina_sequencing_g/key-files",
"fastq_link_farm": "/agr/persist/projects/2024_illumina_sequencing_g/fastq-link-farm", …
```

Enable production run from development environment

---

src/agr/gbs_prism/redun/stage2.py
src/agr/redun/tasks/__init__.py
src/agr/redun/tasks/unblind.py

Is an important file for lab staff, and currently its hiding in blind directory.
Refactored out some duplicated calls to `cohort_dir()` and `cohort_blind_dir()`
And also unblind KGD.stdout, which must have fallen off the list when I changed to dictionary-based KGD output.

Unblind TagCountsAndSampleStats.csv

---

pipeline.py
src/agr/gbs_prism/redun/stage2.py
src/agr/gbs_prism/redun/warehouse.py
src/agr/redun/tasks/gupdate.py
src/agr/redun/util.py

The run which will confirm this is fixed is still in progress, but hopefully fixes the missing callrate and sampdepth stats.
Made `await_results` a utility, as we've used it in a couple of places now.

Import stats

---

src/agr/gbs_prism/redun/stage1.py
src/agr/seq/sequencer_run.py

Using CopyComplete.txt rather than RTAComplete.txt as previously, which we recently discovered is incorrect.
I found nothing in the redun docs about task timeout, nor in the source code, so this should happily wait forever (not tested).
Fixes #82

Await run complete

---

src/agr/gbs_prism/summarise_read_and_tag_counts.py

Sometimes cohorts get constructed which are composed of only control samples, these then can result in zero tag_counts when filtered in summarise_read_and_tag_counts.py, which previously would cause an error. Now we return a warning and zero counts for the summary statistics.
Fixes #136

summarise_read_and_tag_counts handles zero tags_reads

---

src/agr/redun/cluster_executor.py
src/agr/redun/tasks/fastqc.py
src/agr/redun/tasks/kgd.py
src/agr/redun/tasks/tassel3.py

This splits up the expected files for `run_job_n` into required and optional, and so far the only use for optional is the KGD high related CSVs.
Fixes #115 
I have tested it a few times, but would like to see a final successful run before merging it.  But I won't have time to do that today.  If you're so inclined, please have a go with it, and if you're happy, go ahead and merge it.

Optional files for kgd

---

src/agr/redun/tasks/keyfiles.py

Keyfiles for walkins are imported correctly and exported with qc ids for downstream processing. This is just a small fix to the path construction of the imported keyfiles when there are walkins keyfiles.

Return correct keyfile paths for walkins keyfiles

---

src/agr/gbs_prism/redun/stage2.py
src/agr/gbs_prism/redun/stage3.py
src/agr/redun/tasks/tassel3.py

As requested y Hayley to allow multiple TagCount.csv files to be open in excel at once.
Tested with run 358 on 21-05-2025.
Fixes #131

prepending cohort to TagCount.csv file names

---

config/eri-executor.jsonnet

I saw a tassel3_TBTToMapInfo job killed, this seems to be what's required.

Slight bump to Tassel3Default job spec

---

README.md
config/redun.dev/redun.ini
config/redun.prod/redun.ini
config/redun.test/redun.ini
flake.nix

To enable this, three gbs_prism_redun databases were deployed on the molten postgres server in eRI, one each for dev, test, prod.  Authorization is as for gquery with Kerberos tickets, so kinit is required before running redun console.
Postgres backend config exists for all three environments, but we probably will only use it for prod.
Now that there is additional `gbs_prism` specific configuration to deal with when switching the development environment between dev, test, and prod, the environment variables have been changed from `GQUERY` prefixed ones to `GBS_PRISM` prefixed, as described in the README.
Fixes #143

Postgres backend for  redun

---

README.md
eri/install
flake.nix
pyproject.toml

The environment module exposes only redun, gquery, and gupdate on the path.  Everything else is hidden away.
Fixes #144 
As soon as this is merged I will actually deploy gbs_prism as a module.

Install script to deploy as an environment module on eRI

---

src/agr/gbs_prism/redun/stage2.py
src/agr/gbs_prism/redun/stage3.py
src/agr/redun/tasks/tassel3.py

Renaming a file which redun knows about will make it unhappy.
Instead we create it in the first place with the correct name.
Fixes #162

Don't rename the TagCount.csv file

---

src/agr/redun/tasks/kgd.py

This has been broken for ages. But was very simple, and nothing to do with lazy expressions in the end.
Fixes #165

Fix gusbase_rdata being looked up in the wrong place in KgdOutput

---

src/agr/redun/tasks/tag_count.py
src/agr/redun/tasks/tassel3.py
src/agr/util/path.py

Only affects cases where ramify_tassel_keyfile creates multiple parts, so e.g. uber keyfiles.

Fix: use split keyfiles rather than original for each ramify'd part

---

src/agr/redun/tasks/tassel3.py

These were removed by mistake, thinking they were the same as the defaults.
Merge after parameterised config

Restore tag limit for MergeTaxaTagCount to legacy values

---

src/agr/redun/tasks/demultiplex.py
src/agr/redun/tasks/tag_count.py

Previously this had been incorrectly coupled with whether there was one or multiple parts returned from ramify_tassel_keyfile.

Add demultiplex parameter merge_taxa for Tassel merge_taxa_tag_count
